M48
; DRILL file {KiCad 8.0.4+dfsg-1} date 2024-09-09T10:41:01+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-09T10:41:01+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4+dfsg-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0454
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X4.015Y-7.7047
X4.3063Y-4.0118
X7.8575Y-7.7047
T2
X6.9638Y-5.7894
X7.8299Y-5.7894
T3
X4.0945Y-4.0748
X7.7945Y-4.0748
M30
